repo:
  url: https://github.com/michaelhenkel/copilot-analytics
  token: /Users/mhenkel/.githubtoken
  localDir: /Users/mhenkel/go/src/github.com/michaelhenkel/copilot-analytics
languages:
- name: go
  extensions:
  - ".go"
  annotation: "// +copilot"
- name: yaml
  extensions:
  - ".yaml"
  annotation: "# +copilot"
commits:
  from: 0a1ac6db0e754efc8d21b521546243ba6eaab394
  to: 38f7c32dffbdea1aaec3ab008dc2ee608e21fb24

  