repo:
  local: /Users/mhenkel/go/src/github.com/michaelhenkel/copilot-analytics
  url: https://github.com/michaelhenkel/copilot-analytics
  #token: /Users/mhenkel/.githubtoken
languages:
- name: go
  extensions:
  - ".go"
  annotation: "// +copilot"
- name: yaml
  extensions:
  - ".yaml"
  annotation: "# +copilot"
#commits:
#  from: 0a1ac6db0e754efc8d21b521546243ba6eaab394
#  to: b873e307c6fd9d2bd2b2141e2699472cf499695a

  